import { createFileRoute, Outlet } from "@tanstack/react-router";
import { SiteLayout } from "@/components/site/Layout";

export const Route = createFileRoute("/rooms")({
  component: RoomsLayout,
});

function RoomsLayout() {
  return <Outlet />;
}

export const rooms = [
  {
    id: "standard-room",
    img: "/images/rooms/standard-room.jpg",
    name: "Standard Room",
    size: "27 m²",
    bedType: "2 Twin / King-size (configurable)",
    view: "Garden view",
    maxOccupancy: 2,
    price: "$125 / night",
    blurb: "A peaceful start to every morning. A cozy, quiet room with natural light and garden-facing windows.",
    amenities: ["A/C", "Wi-Fi", "TV", "Minibar", "Desk", "Bath"],
    gallery: [
      "/images/rooms/standard-room.jpg",
      "/images/rooms/standard-room2.jpg",
      "/images/rooms/standard-room3.jpg",
      "/images/rooms/standard-room4.jpg",
      "/images/rooms/standard-room5.jpg",
      "/images/rooms/standard-room6.jpg",
    ],
  },
  {
    id: "deluxe-room",
    img: "/images/rooms/delux-room.jpg",
    name: "Deluxe Room",
    size: "27 m²",
    bedType: "2 Twin / King-size",
    view: "Courtyard view",
    maxOccupancy: 2,
    price: "$135 / night",
    blurb: "A quiet retreat with courtyard access. Upgraded finishes and a peaceful outlook over the hotel's inner courtyard.",
    amenities: ["A/C", "Wi-Fi", "TV", "Minibar", "Desk", "Bath", "Coffee maker"],
    gallery: [
      "/images/rooms/delux-room.jpg",
      "/images/rooms/delux-room1.jpg",
      "/images/rooms/delux-room2.jpg",
      "/images/rooms/delux-room3.jpg",
      "/images/rooms/delux-room4.jpg",
      "/images/rooms/delux-room5.jpg",
      "/images/rooms/delux-room6.jpg",
      "/images/rooms/delux-room7.jpg",
      "/images/rooms/delux-room8.jpg",
      "/images/rooms/delux-room9.jpg",
    ],
  },
  {
    id: "deluxe-suite",
    img: "/images/rooms/delux-suite.jpg",
    name: "Deluxe Suite",
    size: "39 m²",
    bedType: "1 King-size",
    view: "Panoramic view",
    maxOccupancy: 2,
    price: "$145 / night",
    blurb: "Space to stretch out and unwind. A separate living area and panoramic views make this feel like a true home away from home.",
    amenities: ["A/C", "Wi-Fi", "TV", "Minibar", "Desk", "Bath", "Sitting area"],
    gallery: [
      "/images/rooms/delux-suite.jpg",
      "/images/rooms/delux-suite1.jpg",
      "/images/rooms/delux-suite2.jpg",
      "/images/rooms/delux-suite3.jpg",
      "/images/rooms/delux-suite4.jpg",
      "/images/rooms/delux-suite5.jpg",
      "/images/rooms/delux-suite6.jpg",
      "/images/rooms/delux-suite7.jpg",
      "/images/rooms/delux-suite8.jpg",
      "/images/rooms/delux-suite9.jpg",
    ],
  },
  {
    id: "superior-suite",
    img: "/images/rooms/delux-suite1.jpg", // Fallback to existing image for now
    name: "Superior Suite",
    size: "N/A",
    bedType: "King-size, sitting area included",
    view: "Garden view",
    maxOccupancy: 2,
    price: "$200 / night",
    blurb: "Top-tier comfort with extra space. A generous suite with a dedicated sitting area and lush garden views.",
    amenities: ["A/C", "Wi-Fi", "TV", "Minibar", "Desk", "Bath", "Sitting area", "Coffee maker"],
    gallery: [
      "/images/rooms/delux-suite.jpg",
      "/images/rooms/delux-suite1.jpg",
      "/images/rooms/delux-suite2.jpg",
      "/images/rooms/delux-suite3.jpg",
      "/images/rooms/delux-suite4.jpg",
      "/images/rooms/delux-suite5.jpg",
      "/images/rooms/delux-suite6.jpg",
      "/images/rooms/delux-suite7.jpg",
      "/images/rooms/delux-suite8.jpg",
      "/images/rooms/delux-suite9.jpg",
    ],
  },
  {
    id: "one-bedroom-apartment",
    img: "/images/rooms/two-bedroom-apartment.jpg",
    name: "One Bedroom Apartment",
    size: "73 m²",
    bedType: "King-size",
    view: "Pool view",
    maxOccupancy: 4,
    price: "$180 / night",
    blurb: "Perfect for families or longer stays. Spacious layout with separate living and sleeping areas, overlooking the pool.",
    amenities: ["A/C", "Wi-Fi", "TV", "Minibar", "Desk", "Bath", "Kitchenette"],
    gallery: [
      "/images/rooms/two-bedroom-apartment.jpg",
      "/images/rooms/two-bedroom-apartment1.jpg",
      "/images/rooms/two-bedroom-apartment2.jpg",
      "/images/rooms/two-bedroom-apartment3.jpg",
      "/images/rooms/two-bedroom-apartment4.jpg",
      "/images/rooms/two-bedroom-apartment5.jpg",
      "/images/rooms/two-bedroom-apartment6.jpg",
      "/images/rooms/two-bedroom-apartment7.jpg",
      "/images/rooms/two-bedroom-apartment8.jpg",
    ],
  },
];
