/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PoolRouteImport } from './routes/pool'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as DiningIndexRouteImport } from './routes/dining.index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as DiningEquatoriaRouteImport } from './routes/dining.equatoria'

const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolRoute = PoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const DiningIndexRoute = DiningIndexRouteImport.update({
  id: '/dining/',
  path: '/dining/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomsRoute,
} as any)
const DiningEquatoriaRoute = DiningEquatoriaRouteImport.update({
  id: '/dining/equatoria',
  path: '/dining/equatoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/pool': typeof PoolRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spa': typeof SpaRoute
  '/dining/equatoria': typeof DiningEquatoriaRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/dining/': typeof DiningIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/pool': typeof PoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spa': typeof SpaRoute
  '/dining/equatoria': typeof DiningEquatoriaRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/dining': typeof DiningIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/pool': typeof PoolRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spa': typeof SpaRoute
  '/dining/equatoria': typeof DiningEquatoriaRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/dining/': typeof DiningIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experiences'
    | '/gallery'
    | '/pool'
    | '/rooms'
    | '/sitemap.xml'
    | '/spa'
    | '/dining/equatoria'
    | '/rooms/$roomId'
    | '/dining/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experiences'
    | '/gallery'
    | '/pool'
    | '/sitemap.xml'
    | '/spa'
    | '/dining/equatoria'
    | '/rooms/$roomId'
    | '/dining'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experiences'
    | '/gallery'
    | '/pool'
    | '/rooms'
    | '/sitemap.xml'
    | '/spa'
    | '/dining/equatoria'
    | '/rooms/$roomId'
    | '/dining/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRoute
  GalleryRoute: typeof GalleryRoute
  PoolRoute: typeof PoolRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpaRoute: typeof SpaRoute
  DiningEquatoriaRoute: typeof DiningEquatoriaRoute
  DiningIndexRoute: typeof DiningIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool': {
      id: '/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof PoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/dining/': {
      id: '/dining/'
      path: '/dining'
      fullPath: '/dining/'
      preLoaderRoute: typeof DiningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/dining/equatoria': {
      id: '/dining/equatoria'
      path: '/dining/equatoria'
      fullPath: '/dining/equatoria'
      preLoaderRoute: typeof DiningEquatoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RoomsRouteChildren {
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRoute,
  GalleryRoute: GalleryRoute,
  PoolRoute: PoolRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpaRoute: SpaRoute,
  DiningEquatoriaRoute: DiningEquatoriaRoute,
  DiningIndexRoute: DiningIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
